# Configurando Service

apiVersion: v1
kind: Service
metadata:
  name: svc-pod-1
spec:
  type: NodePort # Funciona como o ClusterIP, porém faz a comunicação também fora do cluster
  ports:
    - port: 80 
      #targetPort: 80
      nodePort: 30000
  selector:
    app: primeiro-pod # Referencia da label criada no Pod