# Configurando LoadBalancer

# LoadBalancernada mais é do que um ClusterIP que permite a comunicação
# entre uma máquina do mundo externo e os nosso pods.
# Só que ele automaticamente se integra ao LoadBalancerdo nosso cloud provider.

# Por serem um Load Balancer, também são um NodePort e ClusterIP ao mesmo tempo

apiVersion: v1
kind: Service
metadata:
  name: svc-pod-loadbalancer-1
spec:
  type: LoadBalancer
  ports:
    - port: 80
      nodePort: 30000
  selector:
    app: primeiro-pod